scan_matcher:
  ros__parameters:
    use_sim_time: true
    global_frame_id: "track"
    odom_frame_id: "odom"
    robot_frame_id: "base_footprint"
    registration_method: "NDT"
    ndt_resolution: 1.0
    ndt_num_threads: 2
    # gicp_corr_dist_threshold: 2.0
    trans_for_mapupdate: 0.3
    vg_size_for_input: 0.2
    vg_size_for_map: 0.1
    use_min_max_filter: true
    scan_min_range: 2.5
    scan_max_range: 50.0
    scan_period: 0.1
    map_publish_period: 1.0
    num_targeted_cloud: 100
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: true
    debug_flag: false

graph_based_slam:
  ros__parameters:
    use_sim_time: true
    global_frame_id: "track"
    registration_method: "NDT"
    ndt_resolution: 1.0
    ndt_num_threads: 2
    voxel_leaf_size: 0.05
    loop_detection_period: 3000  # nanosec
    threshold_loop_closure_score: 0.5
    distance_loop_closure: 10.0
    range_of_searching_loop_closure: 30.0
    search_submap_num: 100  # needs to be <120
    num_adjacent_pose_cnstraints: 50
    use_save_map_in_loop: false
    debug_flag: true
